# Site settings
title: Dartron's Profile
email: hello@test.io
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages"
url: "http://dartron.github.io"
twitter_username: twitter
github_username:  github
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
